main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Awards
    url: '#awards'
    weight: 20
  - name: Experience
    url: '#experience'
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 60
  - name: CV
    url: uploads/resume.pdf
    weight: 70